onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/clk
add wave -noupdate /testbench/resetn
add wave -noupdate /testbench/trap
add wave -noupdate /testbench/mem_valid
add wave -noupdate /testbench/mem_instr
add wave -noupdate /testbench/mem_ready
add wave -noupdate /testbench/mem_addr
add wave -noupdate /testbench/mem_wdata
add wave -noupdate /testbench/mem_wstrb
add wave -noupdate /testbench/mem_rdata
add wave -noupdate /testbench/uut/clk
add wave -noupdate /testbench/uut/resetn
add wave -noupdate /testbench/uut/trap
add wave -noupdate /testbench/uut/mem_valid
add wave -noupdate /testbench/uut/mem_instr
add wave -noupdate /testbench/uut/mem_addr
add wave -noupdate /testbench/uut/mem_wdata
add wave -noupdate /testbench/uut/mem_wstrb
add wave -noupdate /testbench/uut/mem_rdata
add wave -noupdate /testbench/uut/mem_la_read
add wave -noupdate /testbench/uut/mem_la_write
add wave -noupdate /testbench/uut/mem_la_addr
add wave -noupdate /testbench/uut/mem_la_wdata
add wave -noupdate /testbench/uut/mem_la_wstrb
add wave -noupdate /testbench/uut/pcpi_valid
add wave -noupdate /testbench/uut/trace_valid
add wave -noupdate /testbench/uut/trace_data
add wave -noupdate /testbench/uut/count_cycle
add wave -noupdate /testbench/uut/count_instr
add wave -noupdate /testbench/uut/reg_pc
add wave -noupdate /testbench/uut/reg_next_pc
add wave -noupdate /testbench/uut/reg_op1
add wave -noupdate /testbench/uut/reg_op2
add wave -noupdate /testbench/uut/reg_out
add wave -noupdate /testbench/uut/reg_sh
add wave -noupdate /testbench/uut/next_insn_opcode
add wave -noupdate /testbench/uut/dbg_insn_opcode
add wave -noupdate /testbench/uut/dbg_insn_addr
add wave -noupdate /testbench/uut/dbg_mem_valid
add wave -noupdate /testbench/uut/dbg_mem_instr
add wave -noupdate /testbench/uut/dbg_mem_ready
add wave -noupdate /testbench/uut/dbg_mem_addr
add wave -noupdate /testbench/uut/dbg_mem_wdata
add wave -noupdate /testbench/uut/dbg_mem_wstrb
add wave -noupdate /testbench/uut/dbg_mem_rdata
add wave -noupdate /testbench/uut/decoded_rd
add wave -noupdate /testbench/uut/decoded_rs1
add wave -noupdate /testbench/uut/decoded_rs2
add wave -noupdate /testbench/uut/decoded_imm
add wave -noupdate /testbench/uut/decoded_imm_j
add wave -noupdate /testbench/uut/cpu_state
add wave -noupdate /testbench/uut/irq_state
add wave -noupdate /testbench/uut/current_pc
add wave -noupdate /testbench/uut/cpuregs_write
add wave -noupdate /testbench/uut/cpuregs_wrdata
add wave -noupdate /testbench/uut/cpuregs_rs1
add wave -noupdate /testbench/uut/cpuregs_rs2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {2048 ns}
